"use client";
import { useEffect, useState } from "react";
import { SlidersHorizontal } from "lucide-react";
import { VenueCard } from "@/components/marketplace/venue-card";
const cities=["Delhi","Mumbai","Lucknow","Kanpur","Jaipur","Agra","Bangalore","Hyderabad","Chandigarh"];
const types=["Banquet Hall","Wedding Lawn","Resort","Hotel","Farmhouse","Palace"];
export default function VenuesPage(){const [items,setItems]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [params,setParams]=useState(()=>new URLSearchParams(typeof window!=="undefined"?window.location.search:""));
 const load=async()=>{setLoading(true);const res=await fetch(`/api/venues?${params.toString()}`,{cache:"no-store"});const data=await res.json();setItems(data.items||[]);setLoading(false)};useEffect(()=>{load()},[params.toString()]);
 const set=(key:string,val:string)=>setParams(prev=>{const n=new URLSearchParams(prev);if(val)n.set(key,val);else n.delete(key);return n});
 return <main className="min-h-screen bg-ivory px-5 pb-24 pt-32 sm:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.3em] text-gold">Find your setting</p><h1 className="mt-3 font-display text-5xl sm:text-6xl">Wedding venues made for your moment.</h1><p className="mt-5 text-charcoal/60">Explore real marketplace listings from the Viwah database and narrow them down by city, budget, capacity and style.</p></div><div className="mt-10 rounded-[2rem] border border-charcoal/10 bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-5"><input className="field" placeholder="Search venues..." defaultValue={params.get("q")||""} onChange={e=>set("q",e.target.value)}/><select className="field" value={params.get("city")||""} onChange={e=>set("city",e.target.value)}><option value="">All cities</option>{cities.map(x=><option key={x}>{x}</option>)}</select><select className="field" value={params.get("venueType")||""} onChange={e=>set("venueType",e.target.value)}><option value="">All venue types</option>{types.map(x=><option key={x}>{x}</option>)}</select><select className="field" value={params.get("minCapacity")||""} onChange={e=>set("minCapacity",e.target.value)}><option value="">Any capacity</option><option value="200">200+ guests</option><option value="400">400+ guests</option><option value="600">600+ guests</option></select><select className="field" value={params.get("sort")||"featured"} onChange={e=>set("sort",e.target.value)}><option value="featured">Featured</option><option value="price_asc">Price: low to high</option><option value="price_desc">Price: high to low</option><option value="rating">Top rated</option><option value="popular">Most reviewed</option></select></div></div><div className="mt-10 flex items-center justify-between"><p className="text-sm text-charcoal/55"><SlidersHorizontal className="mr-2 inline" size={16}/>Showing {items.length} venues</p></div>{loading?<div className="mt-6 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{[1,2,3].map(x=><div key={x} className="h-[440px] animate-pulse rounded-[2rem] bg-white"/>)}</div>:items.length?<div className="mt-6 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{items.map(v=><VenueCard key={v._id} venue={v}/>)}</div>:<div className="mt-8 rounded-[2rem] bg-white p-12 text-center"><h2 className="font-display text-3xl">No venues found</h2><p className="mt-2 text-charcoal/55">Try another city, venue type or search term.</p></div>}</div></main>}
