"use client";
import { useEffect, useState } from "react";
import AdminShell,{Card,PageHeader} from "../../../components/admin/admin-shell";

const categories=["Photographer","Makeup Artist","Decorator","Caterer","Mehendi Artist","DJ"];
type Option={label:string;value:number};
const fallback:Record<string,Option[]>={
 Photographer:[{label:"Under ₹50k",value:50000},{label:"Under ₹1L",value:100000},{label:"Under ₹2L",value:200000},{label:"Under ₹5L",value:500000}],
 "Makeup Artist":[{label:"Under ₹50k",value:50000},{label:"Under ₹1L",value:100000},{label:"Under ₹2L",value:200000},{label:"Under ₹5L",value:500000}],
 Decorator:[{label:"Under ₹50k",value:50000},{label:"Under ₹1L",value:100000},{label:"Under ₹2L",value:200000},{label:"Under ₹5L",value:500000}],
 Caterer:[{label:"Under ₹500 / plate",value:500},{label:"Under ₹750 / plate",value:750},{label:"Under ₹1,000 / plate",value:1000},{label:"Under ₹1,500 / plate",value:1500}],
 "Mehendi Artist":[{label:"Under ₹10k",value:10000},{label:"Under ₹20k",value:20000},{label:"Under ₹30k",value:30000},{label:"Under ₹50k",value:50000}],
 DJ:[{label:"Under ₹50k",value:50000},{label:"Under ₹1L",value:100000},{label:"Under ₹2L",value:200000},{label:"Under ₹5L",value:500000}],
};
function PasswordForm(){ const [currentPassword,setCurrentPassword]=useState(""); const [newPassword,setNewPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [status,setStatus]=useState(""); const [saving,setSaving]=useState(false); async function submit(){setStatus(""); if(newPassword.length<10)return setStatus("Password must be at least 10 characters."); if(newPassword!==confirm)return setStatus("New passwords do not match."); setSaving(true); try{const r=await fetch("/api/admin/change-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword,newPassword})});const d=await r.json();setStatus(r.ok?"Password changed successfully.":d.error||"Unable to change password.");if(r.ok){setCurrentPassword("");setNewPassword("");setConfirm("")}}catch{setStatus("Unable to change password.")}finally{setSaving(false)}} return <div className="mt-5 grid gap-3 md:grid-cols-3"><input type="password" placeholder="Current password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} className="rounded-xl border px-4 py-3"/><input type="password" placeholder="New password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} className="rounded-xl border px-4 py-3"/><input type="password" placeholder="Confirm new password" value={confirm} onChange={e=>setConfirm(e.target.value)} className="rounded-xl border px-4 py-3"/><div className="md:col-span-3 flex flex-wrap items-center gap-3"><button type="button" onClick={submit} disabled={saving} className="rounded-xl border border-[#c8a45d] px-5 py-3 text-sm font-semibold text-[#8a6a2f] disabled:opacity-60">{saving?"Updating…":"Change password"}</button>{status&&<span className="text-sm text-black/55">{status}</span>}</div></div> }

export default function Settings(){
 const [active,setActive]=useState("Photographer"); const [vendor,setVendor]=useState<Record<string,Option[]>>(fallback); const [venue,setVenue]=useState<Option[]>([{label:"Under ₹1L",value:100000},{label:"Under ₹2L",value:200000},{label:"Under ₹5L",value:500000},{label:"Under ₹10L",value:1000000}]); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
 useEffect(()=>{fetch("/api/admin/settings").then(r=>r.json()).then(d=>{if(d.vendorPriceOptions)setVendor(d.vendorPriceOptions);if(d.venuePriceOptions?.length)setVenue(d.venuePriceOptions)}).catch(()=>{})},[]);
 const update=(cat:string,i:number,key:"label"|"value",value:string)=>setVendor(v=>({...v,[cat]:v[cat].map((o,idx)=>idx===i?{...o,[key]:key==="value"?Number(value):value}:o)}));
 const save=async()=>{setSaving(true);setMessage("");const r=await fetch("/api/admin/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({vendorPriceOptions:vendor,venuePriceOptions:venue})});setMessage(r.ok?"Marketplace pricing settings saved.":"Unable to save settings.");setSaving(false)};
 return <AdminShell><PageHeader title="Settings" description="Control marketplace behaviour and pricing filters without changing code."/><div className="grid gap-6 xl:grid-cols-[240px_1fr]"><Card className="p-3 h-fit"><p className="px-3 py-2 text-xs font-semibold uppercase tracking-widest text-black/40">Vendor categories</p>{categories.map(c=><button key={c} onClick={()=>setActive(c)} className={`w-full rounded-xl px-3 py-3 text-left text-sm ${active===c?"bg-[#f1e6cf] font-semibold text-[#8a6a2f]":"hover:bg-black/[.03]"}`}>{c}</button>)}</Card><Card className="p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="font-serif text-2xl">{active} price filters</h2><p className="mt-1 text-sm text-black/50">These options appear on the public marketplace and home search.</p></div><button onClick={save} disabled={saving} className="rounded-xl bg-[#c8a45d] px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{saving?"Saving…":"Save settings"}</button></div><div className="mt-6 space-y-3">{(vendor[active]||[]).map((o,i)=><div key={i} className="grid gap-3 sm:grid-cols-[1fr_180px]"> <input value={o.label} onChange={e=>update(active,i,"label",e.target.value)} className="rounded-xl border px-4 py-3"/><input type="number" min="0" value={o.value} onChange={e=>update(active,i,"value",e.target.value)} className="rounded-xl border px-4 py-3"/></div>)}</div>{active==="Caterer"&&<p className="mt-4 rounded-xl bg-[#faf7f2] p-4 text-sm text-black/60">Use labels such as “Under ₹750 / plate” when managing caterer filters. The actual vendor price is controlled per vendor.</p>}<div className="mt-10 border-t pt-6"><h3 className="font-serif text-xl">Change admin password</h3><p className="mt-1 text-sm text-black/50">Your current password is required. Use at least 10 characters.</p><PasswordForm /></div><div className="mt-10 border-t pt-6"><h3 className="font-serif text-xl">Venue price filters</h3><div className="mt-4 space-y-3">{venue.map((o,i)=><div key={i} className="grid gap-3 sm:grid-cols-[1fr_180px]"><input value={o.label} onChange={e=>setVenue(v=>v.map((x,idx)=>idx===i?{...x,label:e.target.value}:x))} className="rounded-xl border px-4 py-3"/><input type="number" min="0" value={o.value} onChange={e=>setVenue(v=>v.map((x,idx)=>idx===i?{...x,value:Number(e.target.value)}:x))} className="rounded-xl border px-4 py-3"/></div>)}</div></div>{message&&<p className="mt-5 rounded-xl bg-[#f1e6cf] px-4 py-3 text-sm text-[#6d5426]">{message}</p>}</Card></div></AdminShell>;
}
