import { NextResponse } from "next/server";
import { connectDB } from "../../../../lib/db";
import { Venue } from "../../../../models";
import { getAdminSession } from "../../../../lib/admin-auth";
import { z } from "zod";
const escapeRegex=(value:string)=>value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");
const schema=z.object({name:z.string().min(2),city:z.string().min(2),location:z.string().min(2),description:z.string().min(10),images:z.array(z.string().url()),startingPrice:z.coerce.number().min(0),capacity:z.coerce.number().min(1),venueType:z.enum(["Banquet Hall","Wedding Lawn","Resort","Hotel","Farmhouse","Palace"]),amenities:z.array(z.string()),rating:z.coerce.number().min(0).max(5),reviewCount:z.coerce.number().min(0),featured:z.boolean(),status:z.enum(["active","inactive"])});
const slugify=(s:string)=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
export async function GET(request:Request){if(!(await getAdminSession()))return NextResponse.json({error:"Unauthorized"},{status:401});await connectDB();const {searchParams}=new URL(request.url);const q=searchParams.get("q")||"";const city=searchParams.get("city")||"";const status=searchParams.get("status")||"";const page=Math.max(1,Number(searchParams.get("page")||1));const limit=10;const filter:any={};if(q)filter.$or=[{name:new RegExp(escapeRegex(q),"i")},{city:new RegExp(escapeRegex(q),"i")}];if(city)filter.city=city;if(status)filter.status=status;const [items,total]=await Promise.all([Venue.find(filter).sort({createdAt:-1}).skip((page-1)*limit).limit(limit).lean(),Venue.countDocuments(filter)]);return NextResponse.json({items,total,page,pages:Math.ceil(total/limit)});}
export async function POST(request:Request){if(!(await getAdminSession()))return NextResponse.json({error:"Unauthorized"},{status:401});try{const data=schema.parse(await request.json());await connectDB();const base=slugify(data.name);let slug=base,i=1;while(await Venue.exists({slug}))slug=`${base}-${i++}`;const item=await Venue.create({...data,slug});return NextResponse.json({item},{status:201});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Invalid venue data"},{status:400});}}
